### ISSUE TITLE
PHP Fatal error in MediaWiki 1.42.

### ISSUE THREAD

**Issue by XXY233** [RazeSoldier/MediaWiki-extension-QCloudStorage#2]
Hello! I don't know if you are still interested in maintaining this project. I'm sorry if I bothered you. The extension does not work in MediaWiki 1.42.1, and my php version is 8.2.20 (apache2handler).

**[Wed Aug 07 02:37:50.471419 2024] [php:error] [pid 26723:tid 26723] [client 127.0.0.1:18157] PHP Fatal error:  Class RazeSoldier\\MWQCloudStorage\\QCloudFileBackend contains 1 abstract method and must therefore be declared abstract or implement the remaining methods (FileBackendStore::doMoveInternal) in /var/lib/mediawiki/extensions/QCloudStorage/includes/QCloudFileBackend.php on line 29, referer: http://localhost/mediawiki/index.php?title=%E7%94%A8%E6%88%B7:Yang&veaction=edit**

**Comment by RazeSoldier** [comment]
Should be fixed
